# docker-compose.yml (改訂版)
version: '3.8'

services:
  # バックエンドサービス
  backend:
    build:
      context: ./backend  # 1. ビルドの基準となる場所はここ（変更なし）
      dockerfile: ../docker/backend/Dockerfile # 2. Dockerfileの場所を明示的に指定
    container_name: exam_app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # フロントエンドサービス
  frontend:
    build:
      context: ./frontend # 1. ビルドの基準となる場所はここ（変更なし）
      dockerfile: ../docker/frontend/Dockerfile # 2. Dockerfileの場所を明示的に指定
    container_name: exam_app_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    command: npm run dev

  # データベースサービス (変更なし)
  db:
    image: postgres:15-alpine
    container_name: exam_db_postgres
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_password
      POSTGRES_DB: exam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: