"""Refactor FK names and adjust cascade for soft delete

Revision ID: 2909f1129102
Revises: 45e2b7cbbf2e
Create Date: 2025-06-12 13:52:40.841511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2909f1129102'
down_revision: Union[str, None] = '45e2b7cbbf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    # ### end Alembic commands ###
